// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jppjdfmeblnmfdowpumn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcGpkZm1lYmxubWZkb3dwdW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjIwMDMsImV4cCI6MjA3MjkzODAwM30.wsqzOYIJ6W17jW9HjqJ0Fjg85cPb5VPni66Ey80gKno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});